### List out activities - but only the data we care about
GRAPHQL https://apigee-prod.api-wr.com/wx/v1/bff/graphql
Accept: application/json, text/plain, */*
api-version: 2
Authorization: Bearer {{token}}
client_id: {{client_id}}
Content-Type: application/json;charset=UTF-8
Origin: https://www.woolworthsrewards.com.au
Referer: https://www.woolworthsrewards.com.au/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

< ./src/RewardsActivityFeed.graphql

### Fetch receipt details
POST https://api.woolworthsrewards.com.au/wx/v1/rewards/member/ereceipts/transactions/details
accept: application/json, text/plain, */*
api-version: 2
Authorization: Bearer {{token}}
client_id: {{client_id}}
content-type: application/json; charset=utf-8
origin: https://www.woolworthsrewards.com.au
referer: https://www.woolworthsrewards.com.au/
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36

{"receiptKey":"{{receiptKey}}"}
